# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/wipe1801/cpuyesklar/cpuyesklar.cache/wt [current_project]
set_property parent.project_path C:/Users/wipe1801/cpuyesklar/cpuyesklar.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/wipe1801/cpuyesklar/cpuyesklar.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/wipe1801/cpuyesklar/cpuyesklar.srcs/sources_1/new/4or.vhd
  C:/Users/wipe1801/cpuyesklar/cpuyesklar.srcs/sources_1/new/add4.vhd
  C:/Users/wipe1801/cpuyesklar/cpuyesklar.srcs/sources_1/new/and4.vhd
  C:/Users/wipe1801/Documents/Task_0/clock_divider.vhd
  C:/Users/wipe1801/cpuyesklar/cpuyesklar.srcs/sources_1/new/cpu4.vhd
  C:/Users/wipe1801/cpuyesklar/cpuyesklar.srcs/sources_1/new/invert4.vhd
  C:/Users/wipe1801/cpuyesklar/cpuyesklar.srcs/sources_1/new/mul4.vhd
  C:/Users/wipe1801/Documents/Task_0/segmentdecoder.vhd
  C:/Users/wipe1801/Documents/Task_0/segmentdriver.vhd
  C:/Users/wipe1801/Downloads/Task3.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/wipe1801/Documents/Task_0/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/wipe1801/Documents/Task_0/Basys3_Master.xdc]


synth_design -top cpu_top_module -part xc7a35tcpg236-1


write_checkpoint -force -noxdef cpu_top_module.dcp

catch { report_utilization -file cpu_top_module_utilization_synth.rpt -pb cpu_top_module_utilization_synth.pb }
